
package gpa_caculator;


/**
 *
 * @author BlackC{}de
 */
public class GPA extends javax.swing.JFrame {

    /**
     * Creates new form GPA
     */
    public GPA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Javatf = new javax.swing.JTextField();
        Systemtf = new javax.swing.JTextField();
        Mathtf = new javax.swing.JTextField();
        Specialtf = new javax.swing.JTextField();
        PNPtf = new javax.swing.JTextField();
        Africatf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JavaPointtf = new javax.swing.JTextField();
        MathPointtf = new javax.swing.JTextField();
        SpecialPointtf = new javax.swing.JTextField();
        SystemPointtf = new javax.swing.JTextField();
        PNPPointtf = new javax.swing.JTextField();
        AfricaPointtf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        GPAtf = new javax.swing.JTextField();
        CALButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SPECIAL EDUCATION:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ICT DEPARMENT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 36, 170, 49);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UEW STUDENT GPA CALCULATOR");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(89, 13, 320, 49);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SUBJECT");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(79, 105, 63, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OOP JAVA:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(79, 151, 109, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRINCIPLE OF TEACHING:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(6, 332, 160, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" SYSTEM ANALYIS:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(59, 195, 113, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COMPUTER MATH:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(61, 233, 111, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SPECIAL EDUCATION:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(29, 279, 140, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AFRICA STUDIES:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(61, 377, 110, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GRADE");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(219, 105, 49, 17);

        Javatf.setBackground(new java.awt.Color(204, 204, 255));
        Javatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavatfActionPerformed(evt);
            }
        });
        jPanel2.add(Javatf);
        Javatf.setBounds(219, 139, 60, 30);

        Systemtf.setBackground(new java.awt.Color(204, 204, 255));
        Systemtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemtfActionPerformed(evt);
            }
        });
        jPanel2.add(Systemtf);
        Systemtf.setBounds(219, 193, 60, 30);

        Mathtf.setBackground(new java.awt.Color(204, 204, 255));
        Mathtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathtfActionPerformed(evt);
            }
        });
        jPanel2.add(Mathtf);
        Mathtf.setBounds(219, 231, 60, 30);

        Specialtf.setBackground(new java.awt.Color(204, 204, 255));
        Specialtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialtfActionPerformed(evt);
            }
        });
        jPanel2.add(Specialtf);
        Specialtf.setBounds(219, 277, 60, 30);

        PNPtf.setBackground(new java.awt.Color(204, 204, 255));
        PNPtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNPtfActionPerformed(evt);
            }
        });
        jPanel2.add(PNPtf);
        PNPtf.setBounds(219, 327, 60, 30);

        Africatf.setBackground(new java.awt.Color(204, 204, 255));
        Africatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfricatfActionPerformed(evt);
            }
        });
        jPanel2.add(Africatf);
        Africatf.setBounds(219, 372, 60, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GRADE PIONT");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(370, 110, 120, 17);

        JavaPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JavaPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(JavaPointtf);
        JavaPointtf.setBounds(372, 139, 100, 30);

        MathPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MathPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(MathPointtf);
        MathPointtf.setBounds(370, 240, 100, 30);

        SpecialPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(SpecialPointtf);
        SpecialPointtf.setBounds(370, 280, 100, 30);

        SystemPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(SystemPointtf);
        SystemPointtf.setBounds(370, 190, 100, 30);

        PNPPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNPPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(PNPPointtf);
        PNPPointtf.setBounds(370, 330, 100, 30);

        AfricaPointtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfricaPointtfActionPerformed(evt);
            }
        });
        jPanel2.add(AfricaPointtf);
        AfricaPointtf.setBounds(370, 370, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MY GPA:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(282, 423, 77, 22);

        GPAtf.setEditable(false);
        GPAtf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GPAtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPAtfActionPerformed(evt);
            }
        });
        jPanel2.add(GPAtf);
        GPAtf.setBounds(369, 418, 85, 38);

        CALButton.setBackground(new java.awt.Color(23, 0, 255));
        CALButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CALButton.setForeground(new java.awt.Color(255, 255, 255));
        CALButton.setText("CALCULATE");
        CALButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CALButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CALButton);
        CALButton.setBounds(70, 420, 150, 27);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Folder/unnamed55.png"))); // NOI18N
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setMinimumSize(new java.awt.Dimension(328, 370));
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 0, 520, 510);

        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(0, 0, 510, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JavatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JavatfActionPerformed

    private void SystemtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SystemtfActionPerformed

    private void MathtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MathtfActionPerformed

    private void SpecialtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialtfActionPerformed

    private void PNPtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNPtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNPtfActionPerformed

    private void AfricatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfricatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AfricatfActionPerformed

    private void JavaPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JavaPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JavaPointtfActionPerformed

    private void MathPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MathPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MathPointtfActionPerformed

    private void SpecialPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialPointtfActionPerformed

    private void SystemPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SystemPointtfActionPerformed

    private void PNPPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNPPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNPPointtfActionPerformed

    private void AfricaPointtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfricaPointtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AfricaPointtfActionPerformed

    private void CALButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALButtonActionPerformed
       String OopjavaLetter, SystemanaLetter , CommathLetter, SpecialLetter, PrincipleLetter, AfricaLetter;
    
     
       //MY Variable name
       OopjavaLetter =Javatf.getText();
       SystemanaLetter =Systemtf.getText();
        CommathLetter =Mathtf.getText();
         SpecialLetter =Specialtf.getText();
          PrincipleLetter =PNPtf.getText();
           AfricaLetter=Africatf.getText();
       
           
           
           
           
           if (OopjavaLetter.equals("A")) {
           JavaPointtf.setText( "4.00");
           }
        else if (OopjavaLetter.equals("B+")) {
        JavaPointtf.setText("3.50");
        }
        else if(OopjavaLetter.equals("B")) {
           JavaPointtf.setText("3.00"); 
        }
  
        else if (OopjavaLetter.equals("C+")) {
                   JavaPointtf.setText("2.50"); 

        }
        else if (OopjavaLetter.equals("C")) {
        JavaPointtf.setText("2.00");
        }
        
        else if (OopjavaLetter.equals("D+")) {
        JavaPointtf.setText("1.50");
        }
        
        else if (OopjavaLetter.equals("D")) {
        JavaPointtf.setText("1.00");
        }
        else JavaPointtf.setText("Invalid Grade");
       
           
           
           //Code for System Analysis
            if (SystemanaLetter.equals("A")) {
           SystemPointtf.setText("4.00");
           }
        else if (SystemanaLetter.equals("B+")) {
        SystemPointtf.setText("3.50");
        }
        else if(SystemanaLetter.equals("B")) {
           SystemPointtf.setText("3.00"); 
        }
  
        else if (SystemanaLetter.equals("C+")) {
                   SystemPointtf.setText("2.50"); 

        }
        else if (SystemanaLetter.equals("C")) {
        SystemPointtf.setText("2.00");
        }
        
        else if (SystemanaLetter.equals("D+")) {
        SystemPointtf.setText("1.50");
        }
        
        else if (SystemanaLetter.equals("D")) {
        SystemPointtf.setText("1.00");
        }
        else  SystemPointtf.setText("Invalid Grade");
            
            
            
            // Code for Computer Math
            if (CommathLetter.equals("A")) {
           MathPointtf.setText("4.00");
           }
        else if (CommathLetter.equals("B+")) {
        MathPointtf.setText("3.50");
        }
        else if(CommathLetter.equals("B")) {
           MathPointtf.setText("3.00"); 
        }
  
        else if (CommathLetter.equals("C+")) {
                   MathPointtf.setText("2.50"); 

        }
        else if (CommathLetter.equals("C")) {
        MathPointtf.setText("2.00");
        }
        
        else if (CommathLetter.equals("D+")) {
        MathPointtf.setText("1.50");
        }
        
        else if (CommathLetter.equals("D")) {
        MathPointtf.setText("1.00");
        }
        else MathPointtf.setText("Invalid Grade");
       
            
            
            
            
             //Code for Special Education
            if (SpecialLetter.equals("A")) {
           SpecialPointtf.setText("4.00");
           }
        else if (SpecialLetter.equals("B+")) {
        SpecialPointtf.setText("3.50");
        }
        else if(SpecialLetter.equals("B")) {
           SpecialPointtf.setText("3.00"); 
        }
  
        else if (SpecialLetter.equals("C+")) {
                   SpecialPointtf.setText("2.50"); 

        }
        else if (SpecialLetter.equals("C")) {
        SpecialPointtf.setText("2.00");
        }
        
        else if (SpecialLetter.equals("D+")) {
        SpecialPointtf.setText("1.50");
        
       
        }
        
        else if (SpecialLetter.equals("D")) {
        SpecialPointtf.setText("1.00");
        
       
        }
        else   SpecialPointtf.setText("Invalid Grade");

            
            
            
            
            
            //Code for Principle and Practice
            if (PrincipleLetter.equals("A")) {
           PNPPointtf.setText("4.00");
           }
        else if (PrincipleLetter.equals("B+")) {
        PNPPointtf.setText("3.50");
        }
        else if(PrincipleLetter.equals("B")) {
           PNPPointtf.setText("3.00"); 
        }
  
        else if (PrincipleLetter.equals("C+")) {
                   PNPPointtf.setText("2.50"); 

        }
        else if (PrincipleLetter.equals("C")) {
        PNPPointtf.setText("2.00");
        }
        
        else if (PrincipleLetter.equals("D+")) {
        PNPPointtf.setText("1.50");
        }
        else if (PrincipleLetter.equals("D")) {
        PNPPointtf.setText("1.00");
        }
        
        
        else PNPPointtf.setText("Invalid Grade");
            
            
            
            
            // Africa Studies
            if (AfricaLetter.equals("A")) {
           AfricaPointtf.setText("4.00");
           }
        else if (AfricaLetter.equals("B+")) {
        AfricaPointtf.setText("3.50");
        }
        else if(AfricaLetter.equals("B")) {
            
           AfricaPointtf.setText("3.00"); 
        }
  
        else if (AfricaLetter.equals("C+")) {
                   AfricaPointtf.setText("2.50"); 

        }
        else if (AfricaLetter.equals("C")) {
        AfricaPointtf.setText("2.00");
        }
        
        else if (AfricaLetter.equals("D+")) {
        AfricaPointtf.setText("1.50");
        
        
        }
        else if (AfricaLetter.equals("D")) {
        AfricaPointtf.setText("1.00");
        
        
        }
        
        else AfricaPointtf.setText("Invalid Grade");
            
            
            double credit1 = Double.parseDouble(JavaPointtf.getText());
           double credit2 = Double.parseDouble(SystemPointtf.getText());
           double credit3 = Double.parseDouble(MathPointtf.getText());
           double credit4 = Double.parseDouble(SpecialPointtf.getText());
           double credit5 = Double.parseDouble(PNPPointtf.getText());
           double credit6 = Double.parseDouble(AfricaPointtf.getText());
           
           double creditSum =credit1+credit2+credit3+credit4+credit5+credit6;
          //double multiplyCredit=(credit1)*3.00+(credit2)*3.00+(credit3)*3.00+(credit4)*3.00+(credit5)*3.00+(credit6)*3.00;
          
          double gpa =Math.round(creditSum/6.0);
          //GPAtf.setText("gpa")
            String str = Double.toString(gpa);
            GPAtf.setText(str);
          /*System.out.println(gpa);
          System.out.println(credit1);
          System.out.println(credit2);
          System.out.println(credit3);
          System.out.println(credit4);
          System.out.println(credit5);
          System.out.println(credit6);
          System.out.println(creditSum);
          //System.out.println(multiplyCredit);
            */
          
           //Code for Java Subject
       
            
            
    }//GEN-LAST:event_CALButtonActionPerformed

    private void GPAtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPAtfActionPerformed


    }//GEN-LAST:event_GPAtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AfricaPointtf;
    private javax.swing.JTextField Africatf;
    private javax.swing.JButton CALButton;
    private javax.swing.JTextField GPAtf;
    private javax.swing.JTextField JavaPointtf;
    private javax.swing.JTextField Javatf;
    private javax.swing.JTextField MathPointtf;
    private javax.swing.JTextField Mathtf;
    private javax.swing.JTextField PNPPointtf;
    private javax.swing.JTextField PNPtf;
    private javax.swing.JTextField SpecialPointtf;
    private javax.swing.JTextField Specialtf;
    private javax.swing.JTextField SystemPointtf;
    private javax.swing.JTextField Systemtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
